### PR TITLE
Fix complex attributes

### PR DESCRIPTION
**Pull request by tornqvist**
Complex attribute selectors, e.g. `[class^="hello"]`, would crash due to the attribute being tested against elements which do not have the attribute at all. This adds a check that the attribute is present before trying to match its content.

Also, I enabled the existing attribute tests but skip all the tests for features that are not supported.

### CODE REVIEW

**Comment by tornqvist** [comment]
I also added support for attributes with newlines in them…

**Comment by tornqvist** [comment]
This might be getting out of hand, idk, but it now also fixes matching single class selector against element with multiple classes.

**Comment by goto-bus-stop** [comment]
I'm kinda not wanting to do much open source at the moment, is it OK if i give you commit and publish access and you can just release this yourself? :)

**Comment by tornqvist** [comment]
Sure thing! Take care @goto-bus-stop

**Comment by tornqvist** [comment]
🎉 3.1.0

**Pull request merged**
